FROM resin/%%RESIN_MACHINE_NAME%%-alpine:latest

WORKDIR /app

COPY src/* ./

# Run the configuration script and then wait, so that Resin does not try to
# restart the container
CMD ["sh", "configure.ssh", "&&", "tail", "-f", "/dev/null"]
